// src/components/Layout.js
import React, { useState } from "react";
import styled from "@emotion/styled";
import { Global, css } from "@emotion/core";
import Anchorific from "~/src/assets/Anchorific.svg";
import emotionReset from "emotion-reset";
import Menu from "~src/assets/Menu.svg";
import Sidebar from "./Sidebar.js";

const Wrapper = styled.div`
  margin: auto;
  max-width: 900px;
  position: relative;
`;

const Header = styled.div`
  margin: 20px auto;
  text-align: center;

  @media (min-width: 1300px) {
    margin: auto auto 20px auto;
  }
`;

const SideItem = styled.div`
  width: 20%;
  min-height: 100vh;
  background: #003a6f;
  position: fixed;
  color: white;
  padding: 1.5rem;
  font-weight: normal;
  line-height: 2rem;
  left: 0;
  top: 0;
  display: none;

  @media (min-width: 1300px) {
    display: block;
  }
`;

const MenuItem = styled.button`
  position: absolute;
  left: 20px;
  cursor: pointer;
  background: none;
  border: 0;
`;

const P = styled.p`
  line-height: 1.5;
  margin-bottom: 20px;
  font-weight: 300;

  &.strong {
    font-weight: bold;
  }
`;

const HeaderStuff = styled.div`
  display: block;
  @media (min-width: 1300px) {
    display: none;
  }
`;

const Layout = ({ children }) => {
  const [showNav, setShowNav] = useState(false);

  return (
    <div>
      <Global
        styles={css`
          ${emotionReset}
          html {
            box-sizing: border-box;
          }

          .content {
            @media (min-width: 1300px) {
              display: flex;
              width: 100%;
              flex-direction: row;
              height: 100%;
              min-height: 100vh;
            }
          }

          body {
            background: #003a6f;
            max-width: 850px;
            margin: auto;
            font-family: "Lato", sans-serif;
            font-size: 1.15rem;

            @media (min-width: 1300px) {
              background: #f5f0e6;
            }
          }

          pre[class*="language-"] {
            margin-bottom: 20px;
          }
        `}
      />
      <Sidebar
        show={showNav}
        triggerClose={() => {
          setShowNav(false);
        }}
      />
      <Wrapper>
        <HeaderStuff>
          <MenuItem>
            <Menu
              width="20px"
              height="20px"
              onClick={() => {
                setShowNav((prevState) => !prevState);
              }}
            />
          </MenuItem>
          <Header>
            <Anchorific width="300px" />
          </Header>
        </HeaderStuff>

        <SideItem>
          <Header>
            <Anchorific width="200px" />
          </Header>
          <P>The navigation below is generated by anchorific.</P>
          <div className="sidebar-anchorific"></div>
        </SideItem>
        <main>{children}</main>
      </Wrapper>
    </div>
  );
};

export default Layout;
