// src/pages/home.js
import React from "react";
import Layout from "../components/Layout";
import styled from "@emotion/styled";

const Content = styled.div`
  margin: auto;
  max-width: 900px;
  color: #fff;
  padding: 0 1.2rem;
`;

const Header = styled.h1`
  font-weight: bold;
  font-size: 1.8rem;
  letter-spacing: 2px;
  margin-bottom: 20px;
`;

const H2 = styled.h2`
  font-weight: bold;
  font-size: 1.6rem;
  letter-spacing: 2px;
  margin-bottom: 20px;
`;

const H3 = styled.h3`
  font-weight: bold;
  font-size: 1.3rem;
  letter-spacing: 2px;
  margin-bottom: 20px;
`;

const P = styled.p`
  line-height: 1.5;
  margin-bottom: 20px;
  font-weight: 300;
`;

const A = styled.a`
  color: #42a7ff;

  &:hover {
    color: #7cb8ec;
  }
`;

const Index = () => {
  return (
    <Layout>
      <Content>
        <Header>What is it?</Header>
        <P>
          Anchorific is a jQuery plugin that automatically generates anchored
          headings and nested navigations based on header tags.
        </P>
        <P>
          Checkout the navigation under the hamburger menu. Active state of
          navigation should change based on where you are on the page. The
          navigation is generated by Anchorific.
        </P>
        <Header>Installation</Header>
        <pre>
          <code className="language-bash">npm install --save anchorific</code>
        </pre>
        <P>
          For a guide on how to using jQuery plugins with npm, check out{" "}
          <A href="https://blog.npmjs.org/post/112064849860/using-jquery-plugins-with-npm">
            this blog by NPM.
          </A>
        </P>
        <P>
          You can also use CDN:
          <pre>
            <code className="language-markup">
              &lt;script
              src=&quot;https://cdnjs.cloudflare.com/ajax/libs/anchorific/0.1.2/min/anchorific.min.js&quot;&gt;&lt;/script&gt;
            </code>
          </pre>
        </P>
        <Header>Getting Started</Header>
        <H2>HTML Structure</H2>
        <P>
          You should not skip a level when structuring header tags. H1 should be
          followed by H2, H2 should be followed by H3 and so on. Anchorific
          relies heavily on this particular structure when generating the anchor
          navigation.
        </P>
        <pre>
          <code
            className="language-markup"
            dangerouslySetInnerHTML={{
              __html: `&lt;h1&gt;The Lannisters&lt;/h1&gt;
&lt;h2&gt;Tywin Lanister&lt;/h2&gt;
&lt;h2&gt;Cersei Lannister&lt;/h2&gt;
&lt;h3&gt;Joffrey Baratheon&lt;/h3&gt;
&lt;h3&gt;Myrcella Baratheon&lt;/h3&gt;
&lt;h3&gt;Tommen Baratheon&lt;/h3&gt;
&lt;h2&gt;Jaime Lannister&lt;/h2&gt;
&lt;h2&gt;Tyrion Lannister&lt;/h2&gt;`,
            }}
          ></code>
        </pre>
        <P>
          Based on the HTML markup above, the plugin will generate nested
          navigations like this one:
        </P>
        <pre>
          <code
            className="language-markup"
            dangerouslySetInnerHTML={{
              __html: `&lt;ul&gt;
  &lt;li data-tag=&quot;1&quot;&gt;
    &lt;a href=&quot;#the-lannisters&quot;&gt;The Lannisters&lt;/a&gt;
    &lt;ul&gt;
      &lt;li data-tag=&quot;2&quot;&gt;&lt;a href=&quot;#tywin-lannister&quot;&gt;Tywin Lannister&lt;/a&gt;&lt;/li&gt;
      &lt;li data-tag=&quot;2&quot;&gt;
        &lt;a href=&quot;#cersei-lannister&quot;&gt;Cersei Lannister&lt;/a&gt;
        &lt;ul&gt;
          &lt;li data-tag=&quot;3&quot;&gt;
            &lt;a href=&quot;#joffrey-baratheon&quot;&gt;Joffrey Baratheon&lt;/a&gt;
          &lt;/li&gt;
          &lt;li data-tag=&quot;3&quot;&gt;
            &lt;a href=&quot;#myrcella-baratheon&quot;&gt;Myrcella Baratheon&lt;/a&gt;
          &lt;/li&gt;
          &lt;li data-tag=&quot;3&quot;&gt;&lt;a href=&quot;#tommen-baratheon&quot;&gt;Tommen Baratheon&lt;/a&gt;&lt;/li&gt;
        &lt;/ul&gt;
      &lt;/li&gt;
      &lt;li data-tag=&quot;2&quot;&gt;&lt;a href=&quot;#jaime-lannister&quot;&gt;Jaime Lannister&lt;/a&gt;&lt;/li&gt;
      &lt;li data-tag=&quot;2&quot;&gt;&lt;a href=&quot;#tyrion-lannister&quot;&gt;Tyrion Lannister&lt;/a&gt;&lt;/li&gt;
    &lt;/ul&gt;
  &lt;/li&gt;
&lt;/ul&gt;`,
            }}
          ></code>
        </pre>
        <P>...and it will generate anchored headings like this one:</P>
        <pre>
          <code
            className="language-markup"
            dangerouslySetInnerHTML={{
              __html: `&lt;h1&gt;Tywin Lannister&lt;/h1&gt;
&lt;!-- This would be turn to --&gt;
&lt;h1 id=&quot;tywin-lannister&quot;&gt;
  Tywin Lannister &lt;a href=&quot;#tywin-lannister&quot; class=&quot;anchor&quot;&gt;#&lt;/a&gt;
&lt;/h1&gt;`,
            }}
          ></code>
        </pre>
        <H3>Existing ID</H3>
        <P>Any existing ID will be preserved by the plugin:</P>
        <pre>
          <code
            className="language-markup"
            dangerouslySetInnerHTML={{
              __html: `&lt;h3 id=&quot;what-if-I-already-have-an-id&quot;&gt;What about existing ID?&lt;/h3&gt;
&lt;!-- This would be turn to --&gt;
&lt;h3 id=&quot;what-if-I-already-have-an-id&quot;&gt;
  What about existing ID?&lt;a href=&quot;#what-if-I-already-have-an-id&quot; class=&quot;anchor&quot;&gt;#&lt;/a&gt;
&lt;/h3&gt;`,
            }}
          ></code>
        </pre>
      </Content>
    </Layout>
  );
};

export default Index;
